# Generated by Django 5.2.8 on 2025-11-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramBot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='ФИО')),
                ('city', models.CharField(verbose_name='Город')),
                ('place', models.CharField(verbose_name='Должность')),
                ('organization', models.CharField(verbose_name='Название организации')),
                ('special_code', models.SlugField(verbose_name='Код сотрудника')),
            ],
        ),
        migrations.CreateModel(
            name='Organisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('city', models.CharField(verbose_name='Город')),
                ('director', models.CharField(null=True, verbose_name='Директор')),
                ('users', models.ManyToManyField(related_name='Работники', to='TelegramBot.users')),
            ],
        ),
    ]
